[package]
name = "tdo"
version = "0.1.0"
edition = "2018"
description = "A cli for managing todo lists"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "2.33"
skim = "0.9"
